"""Brand profile generator — uses Claude to create a brand profile from scraped website data.

Takes ScrapedWebsite data and produces a structured brand profile with tone,
audience, do/don't lists, and product catalog.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field

import anthropic

from bot.config import get_settings
from pipeline.scraper import ScrapedWebsite

logger = logging.getLogger(__name__)


@dataclass
class GeneratedBrandProfile:
    """Brand profile generated by Claude from scraped website data."""

    name: str
    tone_words: list[str]
    audience_description: str
    do_list: list[str]
    dont_list: list[str]
    product_catalog: list[dict] = field(default_factory=list)
    compliance_notes: str | None = None
    tagline: str | None = None


def build_brand_prompt(scraped_site: ScrapedWebsite) -> str:
    """Build the prompt for Claude to generate a brand profile from scraped data."""
    sections = [
        f"Website URL: {scraped_site.url}",
        f"Page Title: {scraped_site.title}",
    ]

    if scraped_site.description:
        sections.append(f"Meta Description: {scraped_site.description}")

    if scraped_site.headings:
        sections.append(f"Key Headings: {', '.join(scraped_site.headings[:15])}")

    if scraped_site.products:
        sections.append(f"Products Found: {', '.join(scraped_site.products[:20])}")

    if scraped_site.meta_keywords:
        sections.append(f"Keywords: {', '.join(scraped_site.meta_keywords[:15])}")

    if scraped_site.social_links:
        social_str = ", ".join(f"{k}: {v}" for k, v in scraped_site.social_links.items())
        sections.append(f"Social Media: {social_str}")

    if scraped_site.body_text:
        # Truncate for prompt efficiency
        body = scraped_site.body_text[:4000]
        sections.append(f"Website Content:\n{body}")

    website_info = "\n\n".join(sections)

    return f"""Analyze this business website and create a brand voice profile for social media content creation.

{website_info}

Based on this website, generate a JSON brand profile with these fields:
- "name": The business name
- "tagline": Their tagline or slogan if found (null if not)
- "tone_words": Array of 3-5 adjectives describing their brand voice (e.g., "bold", "playful", "irreverent")
- "audience_description": 1-2 sentence description of their target audience
- "do_list": Array of 3-5 things TO do when writing social content for this brand
- "dont_list": Array of 3-5 things to AVOID when writing social content for this brand
- "product_catalog": Array of products/services, each with "name" and "description"
- "compliance_notes": Any legal/compliance considerations (null if none)

Respond with ONLY valid JSON, no markdown fences or explanation."""


async def generate_brand_profile(
    scraped_site: ScrapedWebsite,
) -> GeneratedBrandProfile:
    """Use Claude to generate a brand profile from scraped website data.

    Args:
        scraped_site: The scraped website data.

    Returns:
        GeneratedBrandProfile with AI-generated brand voice parameters.

    Raises:
        ValueError: If Claude returns invalid JSON.
        anthropic.APIError: If the API call fails.
    """
    settings = get_settings()
    client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)

    prompt = build_brand_prompt(scraped_site)

    response = await client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1500,
        messages=[{"role": "user", "content": prompt}],
    )

    raw_text = response.content[0].text.strip()

    # Parse JSON — handle possible markdown fences
    if raw_text.startswith("```"):
        raw_text = raw_text.split("\n", 1)[1]
        if raw_text.endswith("```"):
            raw_text = raw_text[:-3]
        raw_text = raw_text.strip()

    try:
        data = json.loads(raw_text)
    except json.JSONDecodeError as e:
        logger.error("Claude returned invalid JSON for brand profile", extra={"raw": raw_text[:200]})
        raise ValueError(f"Invalid JSON from Claude: {e}") from e

    return GeneratedBrandProfile(
        name=data.get("name", "Brand"),
        tone_words=data.get("tone_words", []),
        audience_description=data.get("audience_description", ""),
        do_list=data.get("do_list", []),
        dont_list=data.get("dont_list", []),
        product_catalog=data.get("product_catalog", []),
        compliance_notes=data.get("compliance_notes"),
        tagline=data.get("tagline"),
    )
